services:
  mysql:
    image: mysql:8.0
    container_name: property-portal-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: property_portal

    ports:
      - "3307:3306"

    volumes:
      - property_portal_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: property-portal-container

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8090:8080"

    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    restart: unless-stopped

volumes:
  property_portal_mysql_data: